### ISSUE TITLE
breaks when using standard technic

### ISSUE THREAD

**Issue by wsor4035** [Marnack/dlxtrains_modpack#5]
https://github.com/Marnack/dlxtrains_modpack/blob/main/dlxtrains_industrial_wagons/wagons.lua#L157 uses technic.cans api, something only present in https://github.com/h-v-smacker/technic/blob/master/technic/tools/cans.lua , which isnt even listed on cdb. the two common versions of technic listed on cdb do not contain this api method https://github.com/minetest-mods/technic/blob/master/technic/tools/cans.lua and and https://github.com/mt-mods/technic/blob/master/technic/tools/cans.lua

**Comment by Marnack** [comment]
Thanks for the very helpful description of the issue. It should now be fixed in version 1.9.1.
