### ISSUE TITLE
Expose livery information

### ISSUE THREAD

**Issue by y5nw** [Marnack/dlxtrains_modpack#6]
The livery system of DlxTrains does not seem to expose much livery-related information to other mods. As I am currently working on a mod that [extracts information from wagon definitions](https://content.minetest.net/packages/yw05/advtrains_doc_integration/), fetching livery-related information from DlxTrains currently involves some code that is not particularly elegant.

A possible solution would be to move livery information to the wagon definition, similar to how this is done by [doxy's multi-component livery mod](https://invent.kde.org/davidhurka/doxy_mini_tram/-/tree/master/multi_component_liveries). Additionally, it would be nice to have some description on livery schemes.

**Comment by Marnack** [comment]
Hi y5nw,

I know we talked about this briefly in-game many months ago but I wanted to provide you with a status update as well as document it here in the issue thread.

When we last chatted, I mentioned that my goal was to transition dlxtrains to use my [AdvTrains Livery Tools modpack](https://github.com/Marnack/advtrains_livery_tools) which your [advtrains-doc-integration mod](https://codeberg.org/y5nw/advtrains-doc-integration) subsequently now supports.  While my goal is unchanged, I’ve realized while working on it for the last couple of months that it’s a slightly more substantial project than I anticipated and that it will likely be released in phases. While working on the first phase, I noticed that a new data structure that I added temporarily for the duration of the transition period could also be easily used to address your request.  Thus, the next release of dlxtrains will include two new APIs, one to get the count of livery templates for a given wagon type and another to get all of the livery template information for a given wagon type.  This information will include the livery template name, the base texture that you can use for the preview, and notes which you could map to a description field if desired.

Once the transition to AdvTrains Livery Tools is completed (likely many months from now), all livery queries for dlxtrains liveries will need to be done using the AdvTrains Livery Database.  Both your current approach and these new APIs will become obsolete.  While you don’t have to switch to using the new APIs in the interim, it might be safer to do so.  It’s possible, although not too likely, that some of the internal changes I need to make in future phases might break your existing code whereas I will guarantee support for the new APIs until the transition is complete or likely even a bit beyond that as a grace period.

**Comment by Marnack** [comment]
Nice work!

One other item that I should mention is that I will likely need to change how weathering is handled in order to support user customized liveries.  Thus, the technique of simply appending a rotational transformation to the texture may longer be sufficient in the future.  If so, your code would then break.  Unfortunately, I can’t offer an API to protect against that change just yet because I’m still experimenting with several different approaches and, depending on which I choose, the parameters would be different.  So, there’s no action for you to take at the moment but I wanted to let you know about the possibility.
